apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring

spec:
  selector:
    app: grafana
  type: LoadBalancer #NodePort
  ports:
    - port: 80 #3000
      targetPort: 3000
      nodePort: 30001
