kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim-grafana
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

