version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=XXXX.dkr.ecr.eu-west-1.amazonaws.com/fluffy
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd app
      - docker build -t $REPOSITORY_URI:$COMMIT_HASH .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$COMMIT_HASH
      - echo Updating Parameter Store with Prod Docker Image
      - aws ssm put-parameter --name /fluffy/prod/docker-image --value "$REPOSITORY_URI:$COMMIT_HASH" --type String --overwrite