kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql-gp2
provisioner: kubernetes.io/aws-ebs # Amazon EBS CSI driver
parameters:
  type: gp2
  encrypted: 'false' #EBS volumes will always be encrypted
allowVolumeExpansion: true
reclaimPolicy: Retain
mountOptions:
- debug
volumeBindingMode: Immediate
