---
apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "5000"

  #annotations:
  #  prometheus.io/scrape: 'true'
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: fluffy

