kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim-prometheus
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

